from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import (
    BookingCreateView,
    ForgotPasswordView,
    GroupedScreeningsView,
    MovieDetailView,
    TopMovieListView,
    MovieCreateView,
    MovieListView,
    MovieUpdateView,
    MovieDeleteView,
    ResetPasswordView,
    ScreeningDetailView,
    ScreeningFilterView,
    ScreeningListCreateView,
    SeatListView,
    SignUpView,
    SignInView,
    UserBookingListView,
    UserDetailsView,
    UpdateUserView,
    DeleteUserView,
    LogoutView,
    create_order,
    verify_payment,
)

urlpatterns = [
    path("users/signup/", SignUpView.as_view(), name="signup"),
    path("auth/login/", SignInView.as_view(), name="signin"),
    path("auth/forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("auth/reset-password/", ResetPasswordView.as_view(), name="reset-password"),
    path("users/userDetails/", UserDetailsView.as_view(), name="userDetails"),
    path("users/updateUser/", UpdateUserView.as_view(), name="updateUser"),
    path("users/deleteUser/", DeleteUserView.as_view(), name="deleteUser"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/<uuid:movie_id>/", MovieDetailView, name="movie_detail"),
    path("movies/top-movies/", TopMovieListView.as_view(), name="top_movies"),
    path("movies/add/", MovieCreateView.as_view(), name="movie-add"),
    path(
        "movies/<uuid:pk>/update/",
        csrf_exempt(MovieUpdateView.as_view()),
        name="movie-update",
    ),
    path(
        "movies/<uuid:pk>/delete/",
        csrf_exempt(MovieDeleteView.as_view()),
        name="movie-delete",
    ),
    path(
        "movie/screenings/",
        ScreeningListCreateView.as_view(),
        name="screening_list_create",
    ),
    path(
        "movie/screenings/<uuid:pk>/",
        ScreeningDetailView.as_view(),
        name="screening_detail",
    ),
    path(
        "movie/screenings/filter/",
        ScreeningFilterView.as_view(),
        name="screening_filter",
    ),
    path(
        "movie/screenings/grouped/",
        GroupedScreeningsView.as_view(),
        name="grouped_screenings",
    ),
    path(
        "screenings/<uuid:screening_id>/seats/",
        SeatListView.as_view(),
        name="seat-list",
    ),
    path(
        "seats/bookings/",
        csrf_exempt(BookingCreateView.as_view()),
        name="booking-create",
    ),
    path("my-bookings/", UserBookingListView.as_view(), name="user-booking-list"),
    path("create_order/<uuid:booking_id>/", create_order, name="create_order"),
    path("verify_payment/", verify_payment, name="verify"),
]
